//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pluginCalidadMaestro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pluginCalidadMaestro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;
        ///&lt;application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;OMQLTY&quot; FormType=&quot;OMQLTY&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;OMQLTY&quot; title=&quot;Maestro Calidad&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;600&quot; height=&quot;467&quot; client_width=&quot;592&quot; client_height=&quot;376&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;OMQLTY&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OMQLTY {
            get {
                return ResourceManager.GetString("OMQLTY", resourceCulture);
            }
        }
    }
}
