//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreSAPB1.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreSAPB1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;
        ///&lt;application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;Calidad&quot; FormType=&quot;Calidad&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;Calidad&quot; title=&quot;Calidad&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;88&quot; width=&quot;851&quot; height=&quot;491&quot; client_width=&quot;500&quot; client_height=&quot;310&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///     [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Calidad {
            get {
                return ResourceManager.GetString("Calidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;
        ///&lt;application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ComexDir&quot; FormType=&quot;ComexDir&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;ComexDir&quot; title=&quot;Direcciones&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;88&quot; width=&quot;577&quot; height=&quot;234&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///    [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComexDir {
            get {
                return ResourceManager.GetString("ComexDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;
        ///&lt;application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;LotesCalidad&quot; FormType=&quot;LotesCalidad&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;LotesCalidad&quot; title=&quot;Lotes disponibles&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;88&quot; width=&quot;561&quot; height=&quot;334&quot; client_width=&quot;500&quot; client_height=&quot;310&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;DT_3&quot;&gt;
        ///        [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string LotesCalidad {
            get {
                return ResourceManager.GetString("LotesCalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;
        ///&lt;application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;RegEnvase&quot; FormType=&quot;RegEnvase&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;RegEnvase&quot; title=&quot;Registro envase&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;88&quot; width=&quot;300&quot; height=&quot;176&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot;  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string RegEnvase {
            get {
                return ResourceManager.GetString("RegEnvase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;
        ///&lt;application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;RegEnvLote&quot; FormType=&quot;RegEnvLote&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;RegEnvLote&quot; title=&quot;Añadir envases Lote&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;88&quot; width=&quot;285&quot; height=&quot;191&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string RegEnvLote {
            get {
                return ResourceManager.GetString("RegEnvLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;
        ///&lt;application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;RegLote&quot; FormType=&quot;RegLote&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;RegLote&quot; title=&quot;Registro de Lote&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;88&quot; width=&quot;325&quot; height=&quot;179&quot; client_width=&quot;500&quot; client_height=&quot;310&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string RegLote {
            get {
                return ResourceManager.GetString("RegLote", resourceCulture);
            }
        }
    }
}
